### ISSUE TITLE
New release for recent changes related to types

### ISSUE THREAD

**Issue by lawRathod** [nerdvibe/mina-ledger-js#4]
The current release on npm doesn't contain type definitions. The changes to have types on build are now available since ef8768d0857d70f35e76fb068e0f772bf5231e51. 

A new release would help a lot. Thanks! 😄

**Comment by lawRathod** [comment]
Hii @nerdvibe! 😄 

Is it possible to have a new release for this package?

**Comment by nerdvibe** [comment]
Hi @lawRathod sorry for the delay. I totally forgot about publishing the changes on NPM.

The new release with TS types (thanks @t4top ) is published on npm 🙏
